### ISSUE TITLE
Spatial resolution of estimated components doesn't match that of the input data

### ISSUE THREAD

**Issue by eurunuela** [hemolearn/hemolearn#4]
Hi,

I am using Hemolearn to estimate the activity-inducing signal and I have seen that the outputs (5 mm iso) do not have the same spatial resolution as the inputs (2 mm iso). I am using the default HRF atlas.

Is there a way to get Hemolearn to return results with the same spatial resolution as the input? I see there's an option called `atlas_kwargs` but I don't see that the function that generates the mask (and hence, the masker object) receives any input. I don't know if I need to use a different atlas for that.

Thank you for your help.

**Comment by hemolearn** [comment]
Hi @eurunuela !

Yes indeed, the main class (`BDA`) call a  `input_data.NiftiMasker` to convert the nifti into an 2d array. While performing that, it can potentially down-sample the data into the brain mask resolution.

From my perspective, I would advice you to 1/ use `nilearn.masking.compute_brain_mask` on your Nifti to have a properly resolved mask, 2/ to adapt a brain parcellation to this resolution and 3/ define a function that will returned it as: `mask_full_brain, atlas_rois = hrf_atlas(**atlas_kwargs)` (take a look at https://github.com/hemolearn/hemolearn/blob/master/hemolearn/__init__.py#L189 )

Tell me if it helps you. 
Best.

**Comment by eurunuela** [comment]
Hi @hemolearn,

I ended up editing the affines on my own version of the code to make it work with our resolution.

Thank you for your help!
