### ISSUE TITLE
How to get fitted data for every component

### ISSUE THREAD

**Issue by eurunuela** [hemolearn/hemolearn#5]
Hi @hemolearn,

I would like to extract the fitted (i.e., convolved with the HRF) estimates of the activity-inducing signal obtained with `BDA` to compare with our PFM method.

From what I have seen, `BDA` does return the estimated HRFs, but from looking at the code it is not clear how one could convolve the HRFs with the obtained components to get a "fit" of the estimates.

Could you please guide me?

Thank you!

**Comment by hemolearn** [comment]
Hi @eurunuela ,

You can access the estimated HRF like this: `bda_fitted_instance.v_hat`.

To get the denoised BOLD, you can try  this:

```
from nilearn import datasets
from hemolearn import BDA, loss_grad, atlas


def reconstructed_deconvolved_bold(bda_instance):
    """Reconstruct, from the given fitted BDA instance, an inflated
    4D nifti-like image of the estimated denoised BOLD and its associated 2D
    numpy array (1 line = 1 denoised BOLD time serie)."""
    rois_idx, _, _= atlas.split_atlas(bda_instance.hrf_rois)

    X = loss_grad.construct_X_hat_from_v(bda_instance.v_hat,
                                         bda_instance.z_hat,
                                         bda_instance.u_hat,
                                         rois_idx)
    X_img = bda_instance.masker_.inverse_transform(X.T)

    return X_img, X


adhd_dataset = datasets.fetch_adhd(n_subjects=1)
bda = BDA(n_atoms=10, t_r=2.0, n_times_atom=30, max_iter=50, standardize=True)
bda.fit(adhd_dataset.func[0], confound_fnames=adhd_dataset.confounds[0])
X_img, X = reconstructed_deconvolved_bold(bda)
```

Note that I've not intensively checked this code snippet myself. You might have some adaptation to do yourself.

Tell me if it helps!

Best.

**Comment by eurunuela** [comment]
Thank you, that was very helpful!

I managed to do it at the single-component level, which is what I wanted.

I wonder if this could be made clearer in the docs for future users.

Best.

**Comment by hemolearn** [comment]
Hi @eurunuela,

Yeah you're right: I add this to my to-do (along with adding the requirements.txt). I will add this function somewhere (+ an example to illustrate its usage). Thx for your inputs, it helps improving the tool!

Best.

**Comment by eurunuela** [comment]
Happy to share ideas to improve the package 😊
